sonar.projectKey=aupp-lms
sonar.projectName=AUPP LMS Platform
sonar.projectVersion=1.0.0

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/coverage/**,**/*.test.js,terraform/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=coverage/test-reporter.xml
